// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXSulbWyYbbuUHp5IbW3C-3VSlDTtNyiY',
    appId: '1:321144857803:android:f844a04d07ff526d2c274e',
    messagingSenderId: '321144857803',
    projectId: 'astronacci-f4ad6',
    databaseURL: 'https://astronacci-f4ad6-default-rtdb.firebaseio.com',
    storageBucket: 'astronacci-f4ad6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJtJ9WAocOsMy3m5l3iImgyE6eokAKkNs',
    appId: '1:321144857803:ios:f3f45a14c8e991482c274e',
    messagingSenderId: '321144857803',
    projectId: 'astronacci-f4ad6',
    databaseURL: 'https://astronacci-f4ad6-default-rtdb.firebaseio.com',
    storageBucket: 'astronacci-f4ad6.appspot.com',
    iosBundleId: 'com.example.astronacci',
  );
}
